### PR TITLE
Use flatten function to build matrix instead of array slicing syntax

### PR DESCRIPTION
**Pull request by gamcorn**
numpy flatten function was used to replace the array slicing syntax that is not compatible to the latests version of numpy.

### CODE REVIEW

**Review by wilsonrljr — COMMENTED** [review]
Looking good, @gamcorn. I'll release a new update soon and I think we can add your fix on it. I'll merge v0.2.2 to master and ask you to rebase your branch and request again. I'll let you know.

Thank you!

**Comment by wilsonrljr** [comment]
> Looking good, @gamcorn. I'll release a new update soon and I think we can add your fix on it. I'll merge v0.2.2 to master and ask you to rebase your branch and request again. I'll let you know.
> 
> Thank you!

Hey @gamcorn, I merged my updates on master already. Let me know when if/when you can rebase your code with master and push it again so we can follow with your pull request.

**Comment by gamcorn** [comment]
Hello @wilsonrljr, I merged your main on my branch, thanks !

**Review by wilsonrljr — APPROVED** [review]
Looking good. I'm following with the suggestion.

**Comment by wilsonrljr** [comment]
The two tests that failed are simple to fix. The r2_score fail is related to a change I did and the other is a fix you did by using the "mu" instead of "_mu". I'll follow with the merge and I'll fix this two testes myself. Thank you again!

**Pull request merged**
